version: '3.8'

services:
  krakend:
    container_name: api-gateway
    image: devopsfaith/krakend
    ports:
      - "8081:8081"
    volumes:
      -  "./config/krakend/krakend-config.json:/etc/krakend/krakend.json"
  msadmin-marketing:
    container_name: msadmin-marketing
    build: ../msadmin-marketing
    ports:
      - "3001:3001"
  msadmin-support:
    container_name: msadmin-support
    build: ../msadmin-support
    ports:
      - "8001:8000"
  msadmin-company-sales:
    container_name: msadmin-company-sales
    build: ../msadmin-company-sales
    ports:
      - "3000:3000"
  msadmin-users:
    container_name: msadmin-users
    build: ../msadmin-users
    ports:
      - "8000:8000"
